apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bc-frontend
  labels:
    app: bc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc-frontend
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bc-frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: bc-frontend
          image: gcr.io/winbet-blockchain/bc-frontend:v1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '0'
---
apiVersion: v1
kind: Service
metadata:
  name: bc-frontend
spec:
  type: NodePort
  selector:
    app: bc-frontend
  ports:
    - name: tcp
      port: 8080
      targetPort: 3000
---

